fix: trim base64 input before attempting decryption
As the decryption input is base64-encoded, we can safely trim
leading and trailing whitespace from it.

If the input has a newline, it will fail validation, e.g:

```
jwe="$(echo "foobar" | clevis-pin-tpm2 encrypt {})"
echo "${jwe}" | clevis-pin-tpm2 decrypt
Error: Error decrypting JWE

Caused by:
    0: Invalid JWE format: Invalid byte 10, offset 22.
    1: Invalid byte 10, offset 22.
```

Also include additional integration tests written in shell script.

Signed-off-by: Sergio Correia <scorreia@redhat.com>